theme: minima
title: AIChapters
description: Learn AI and Machine Learning through structured courses
baseurl: "/aichapters"
url: "https://sher11.github.io"

# Collections
collections:
  courses:
    output: true
    permalink: /courses/:path/

# Defaults
defaults:
  - scope:
      path: "courses"
    values:
      layout: "chapter"
